apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1
  labels:
    app: my-app1
spec:
  containers:
  - name: my-app1
    image: eragam2295/my-app1:2.1.0
    ports:
    - containerPort: 8080
 
